install.packages('IRkernel')
IRkernel::installspec(user = FALSE)
install.packages('dplyr', lib = "/usr/lib/R/library")
install.packages("tidyverse", lib = "/usr/lib/R/library")
install.packages(c("devtools", "roxygen2", "testthat", "knitr"))
install.packages("RJDBC")
setwd("bazR")
library("devtools")
library(roxygen2)
create("BAZ")
file.copy("/home/app/execHiveQuery.R","/home/app/bazR/BAZ/R/" )
setwd("BAZ")
document()
setwd("..")
install("BAZ")